In [2]:
import numpy as np
import scipy.spatial
import matplotlib.pyplot as plt

In [3]:
pat = 2
sz = 5
patterns = np.zeros([pat, sz])
ct = 0
while ct<pat:
    x = np.random.binomial(size=sz, n=1, p=.5)
    if np.any(np.isin(x, patterns)):
        patterns[ct] = x
        ct += 1
patterns

array([[0., 1., 0., 1., 1.],
       [0., 1., 1., 0., 0.]])

In [4]:
W = (patterns-.5).T.dot(patterns-.5)
W = W - np.diag(np.diag(W))
print(W)

[[ 0.  -0.5  0.   0.   0. ]
 [-0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.  -0.5 -0.5]
 [ 0.   0.  -0.5  0.   0.5]
 [ 0.   0.  -0.5  0.5  0. ]]


In [5]:
y = np.zeros(sz)
ind = np.random.choice(range(pat))

for i, x in enumerate(patterns[ind]):
    if np.random.random() < 0.1:
        y[i] = np.abs(x - 1.)
    else:
        y[i] = x

print(patterns[ind])
print(y)

[0. 1. 1. 0. 0.]
[0. 1. 1. 0. 0.]


In [7]:
x_old = np.array([1, 1, 0, 1, 1])
x_new = np.zeros_like(y)

while ct<50:
    Wx = W.dot(x_old - .5)
    x_new = np.heaviside(Wx, 0.)
    print(x_new)
    x_old = x_new
    ct += 1

print(x_new)

[0. 0. 0. 0. 0.]


In [ ]:
0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 1